apiVersion: v1
kind: ConfigMap
metadata:
  name: easyshop-config
  namespace: easyshop
data:
  MONGODB_URI: "mongodb://mongodb-service:27017/easyshop"
  NODE_ENV: "production"
  NEXT_PUBLIC_API_URL: "https://easyshop.shopitpro.online/api"
  NEXTAUTH_URL: "https://easyshop.shopitpro.online/"
  NEXTAUTH_SECRET: "2YeDcEm7QRyVGLpxs1npDkqRYK+VFlfAiKkZWBqgVXc="
  JWT_SECRET: "1cbcede70394bd3213b25d1bbf4b5333185a81a65a8093bf90aa9aaa46189c34"
