apiVersion: v1
kind: Secret
metadata:
  name: easyshop-secrets
  namespace: easyshop
type: Opaque
stringData:
  JWT_SECRET: "2YeDcEm7QRyVGLpxs1npDkqRYK+VFlfAiKkZWBqgVXc="
  NEXTAUTH_SECRET: "1cbcede70394bd3213b25d1bbf4b5333185a81a65a8093bf90aa9aaa46189c34"
